# TransBot机器人参数配置

# 底盘控制参数
robot:
  # 运动限制
  max_linear_velocity: 1.0      # m/s
  max_angular_velocity: 2.0     # rad/s
  min_linear_velocity: 0.05     # m/s
  min_angular_velocity: 0.1     # rad/s
  
  # 加速度限制
  max_linear_acceleration: 2.0  # m/s²
  max_angular_acceleration: 3.0 # rad/s²
  
  # 底盘尺寸
  wheel_base: 0.2               # 轮距 (m)
  wheel_radius: 0.03            # 轮半径 (m)
  
  # 安全参数
  emergency_stop_deceleration: 5.0  # 紧急停车减速度 (m/s²)
  collision_radius: 0.15        # 碰撞半径 (m)

# 控制器参数
controller:
  # PID参数
  linear_pid:
    kp: 1.0
    ki: 0.1
    kd: 0.05
    
  angular_pid:
    kp: 2.0
    ki: 0.2
    kd: 0.1
  
  # 控制周期
  control_frequency: 20.0       # Hz
  command_timeout: 1.0          # 指令超时时间 (s)

# 传感器参数
sensors:
  # IMU参数
  imu:
    topic: "/imu/data"
    frame_id: "imu_link"
    
  # 里程计参数
  odometry:
    topic: "/odom"
    frame_id: "odom"
    child_frame_id: "base_link"
    
  # 激光雷达参数
  laser:
    topic: "/scan"
    frame_id: "laser_link"
    min_range: 0.1
    max_range: 8.0

# 坐标系参数
tf_frames:
  base_frame: "base_link"
  odom_frame: "odom"
  map_frame: "map"
  camera_frame: "camera_link"
  laser_frame: "laser_link"

# 安全参数
safety:
  enable_collision_detection: true
  collision_check_frequency: 10.0  # Hz
  emergency_stop_enabled: true
  max_tilt_angle: 30.0             # 最大倾斜角度 (度) 